import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";  // <--- INI WAJIB ADA! Kalau hilang, tampilan hancur.

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Julian Bot Panel",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}